[package]
name = "dilbert-feed"
version = "0.1.0"
description = "Enjoy Dilbert in your RSS feed reader without any ads"
authors = ["Mathias Lafeldt <mathias.lafeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/mlafeldt/dilbert-feed"
edition = "2018"

[[bin]]
name = "heartbeat"
path = "heartbeat/lambda.rs"

[dependencies]
lambda_runtime = "0.4"
log = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "1.13"
tokio = "1.9"

[dev-dependencies]
wiremock = "0.5"
