[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "v1.*"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.*"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "v1.*"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "v1.*"

[[constraint]]
  branch = "master"
  name = "github.com/epsagon/epsagon-go"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
