[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "v1.*"

# [[constraint]]
#   name = "github.com/aws/aws-sdk-go"
#   version = "v1.*"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.*"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
