service: dilbert-feed

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  timeout: 20
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::dilbert-feed/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt:
            - DynamoDBTable
            - Arn
  environment:
    BUCKET_NAME: dilbert-feed
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  feed:
    handler: bin/feed
    events:
      - schedule:
          # Run at 00:15 (UTC) every day
          rate: "cron(15 0 * * ? *)"

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
