service: dilbert-feed

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  timeout: 30
  stage: ${opt:stage, 'production'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetBucketLocation
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:service}
        - arn:aws:s3:::${self:service}/*
  environment:
    BUCKET_NAME: ${self:service}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  download-strip:
    handler: bin/download-strip
    events:
      - schedule:
          # Run at 07:45 (UTC) every day
          rate: "cron(45 7 * * ? *)"
  generate-feed:
    handler: bin/generate-feed
    events:
      - schedule:
          # Run at 08:00 (UTC) every day
          rate: "cron(0 8 * * ? *)"
