service: dilbert-feed

provider:
  name: aws
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  runtime: go1.x
  memorySize: 128
  timeout: 30
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: s3:PutObject
      Resource: arn:aws:s3:::${file(serverless-${self:provider.stage}.yml):bucket_name}/*
  environment:
    BUCKET_NAME: ${file(serverless-${self:provider.stage}.yml):bucket_name}
    BUCKET_PREFIX: strips/

package:
  individually: true
  exclude:
    - ./**

functions:
  # These functions are invoked by a state machine managed by Terraform
  get-strip:
    handler: bin/get-strip
    package:
      include: [bin/get-strip]
  gen-feed:
    handler: bin/gen-feed
    environment:
      DOMAIN_NAME: ${file(serverless-${self:provider.stage}.yml):bucket_name}.s3.amazonaws.com
    package:
      include: [bin/gen-feed]
  heartbeat:
    handler: bin/heartbeat
    package:
      include: [bin/heartbeat]
