service: dilbert-feed

provider:
  name: aws
  region: ${env:AWS_REGION}
  stage: production
  runtime: go1.x
  memorySize: 256
  timeout: 30
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [Bucket, Arn]
              - "*"
  environment:
    BUCKET_NAME:
      Ref: Bucket
    BUCKET_PREFIX: strips/
    EPSAGON_TOKEN: ${ssm:/epsagon/token~true}
    EPSAGON_DEBUG: ${env:EPSAGON_DEBUG, "FALSE"}

package:
  individually: true
  exclude:
    - ./**

functions:
  # These functions are invoked by a state machine managed by Terraform
  get-strip:
    handler: bin/get-strip
    package:
      include: [bin/get-strip]
  gen-feed:
    handler: bin/gen-feed
    environment:
      DOMAIN_NAME:
        Fn::GetAtt: [Bucket, DomainName]
    package:
      include: [bin/gen-feed]

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: BucketOwnerFullControl
        BucketName: ${self:service}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LoggingConfiguration:
          DestinationBucketName:
            Ref: LogBucket
        LifecycleConfiguration:
          Rules:
            - Id: DeleteStripsAfter30Days
              Status: Enabled
              Prefix: strips/
              ExpirationInDays: 30
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                - Fn::Join:
                    - "/"
                    - - Fn::GetAtt: [Bucket, Arn]
                      - "*"
    LogBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: LogDeliveryWrite
        BucketName: ${self:service}-logs
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LifecycleConfiguration:
          Rules:
            - Id: DeleteLogsAfter30Days
              Status: Enabled
              ExpirationInDays: 30
