service: dilbert-feed

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::dilbert-feed/*"
  environment:
    BUCKET_NAME: dilbert-feed

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  download:
    handler: bin/download
    events:
      - schedule:
          rate: "cron(0 0/1 * * ? *)"
