name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ZIG_VERSION: 0.9.1
  CARGO_ZIGBUILD_VERSION: 0.5.3

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Set up Rust caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ hashFiles('Cargo.toml', 'Cargo.lock') }}

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Lint Lambda functions
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Test Lambda functions
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Install zig & cargo-zigbuild for cross-compiling
        run: |
          pip3 install ziglang==${ZIG_VERSION}
          curl -fSsL https://github.com/messense/cargo-zigbuild/releases/download/v${CARGO_ZIGBUILD_VERSION}/cargo-zigbuild-v${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz | tar -xzvf- -C "$HOME/.cargo/bin"

      - name: Build Lambda functions
        uses: actions-rs/cargo@v1
        with:
          command: zigbuild
          args: --target aarch64-unknown-linux-gnu.2.17
